### ISSUE TITLE
Inspecting 25 or more teams at a time causes internal server error

### ISSUE THREAD

**Issue by ftctechnh** [adwiii/nc-ftc-inspection-spark#7]
An FTC volunteer was testing the FTC Live software (in anticipation of potentially using it at a Super Regional and/or Championship event).  

He found that if a user tries to inspect 25 or more teams at a time, it causes and internal server error.  He realizes this is an unrealistic test case, but thinks that the system should incorporate some safeguards to prevent a user from getting into this state.

Here are his test notes:
-----------------------------------------------------

> I did find a bug, but I suspect nobody will run into it.  We had 79 teams at our championship and I tried to do inspection forms for all of them (not something anyone sane would do).  However, if you select more 25 teams you get a 500 (internal server error).  Specifically, the stack trace below the signature. I suspect there should be a limit on how many inspection forms (not the Override page) of something like 2-4, more than that and it's not really usable.

----------------- Stack Trace --------------
1. When doing bulk inspection (selected all teams and pressed the inspect selected Teams)
There is a maximum number of teams that you can inspect at once.  It seems like the max number is 26 teams

```
ava.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (unrecognized token: "{")
    at org.sqlite.DB.newSQLException(DB.java:383)
    at org.sqlite.DB.newSQLException(DB.java:387)
    at org.sqlite.DB.throwex(DB.java:374)
    at org.sqlite.NativeDB.prepare(Native Method)
    at org.sqlite.DB.prepare(DB.java:123)
    at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
    at org.sqlite.Conn.prepareStatement(Conn.java:404)
    at org.sqlite.Conn.prepareStatement(Conn.java:399)
    at org.sqlite.Conn.prepareStatement(Conn.java:383)
    at nc.ftc.inspection.dao.EventDAO.getForm(EventDAO.java:425)
    at nc.ftc.inspection.spark.pages.EventPages.inspectionPage(EventPages.java:181)
    at nc.ftc.inspection.spark.pages.EventPages.lambda$4(EventPages.java:211)
    at spark.RouteImpl$1.handle(RouteImpl.java:72)
    at spark.http.matching.Routes.execute(Routes.java:61)
    at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
    at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle(Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Unknown Source)
[qtp883584151-21] ERROR spark.http.matching.GeneralError - 
java.lang.NullPointerException
    at nc.ftc.inspection.spark.pages.EventPages.inspectionPage(EventPages.java:183)
    at nc.ftc.inspection.spark.pages.EventPages.lambda$4(EventPages.java:211)
    at spark.RouteImpl$1.handle(RouteImpl.java:72)
    at spark.http.matching.Routes.execute(Routes.java:61)
    at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
    at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle(Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by adwiii** [comment]
Upon review it seems that the code has a limitation of 26 because it attempts to assign each team a unique letter and then runs out at 26. Fixing that, it can handle up to 64 concurrently but then hits a hard limit that SQL cannot handle more than 64 at a time as currently structured. Since 64 is far more than practically necessary at a time, the system will be updated to allow a maximum of 10 teams at a time, though this limit can be changed.
